###
#
# WindowPanes Configuration
# Arkab portrait display — 1x3 grid
#
###

layout:
  rows: 3
  columns: 1

panes:
  - type: rotating_websites
    position: {row: 1, col: 1}
    proxy: true
    urls:
      - https://www.google.com/maps/@41.7268983,-70.3509357,11z/data=!5m1!1e1?entry=ttu&g_ep=EgoyMDI2MDYyOS4wIKXMDSoASAFQAw%3D%3D
      - https://www.google.com/maps/@42.0906689,-70.9852742,10z/data=!5m1!1e1?entry=ttu&g_ep=EgoyMDI2MDYyOS4wIKXMDSoASAFQAw%3D%3D
      - https://trends.google.com/trends/hottrends/visualize?nrow=5&ncol=5
      - https://www.clockfaceonline.co.uk/clocks/text/

      - https://forecast.weather.gov/MapClick.php?lat=42.31648500000006&lon=-71.10715999999996#.ZGLYV9LMJB0
      - https://www.windy.com/-Weather-radar-radar?radar,42.876,-71.548,7
      - https://www.ventusky.com/?p=42.36;-71.06;6&l=feel
      - https://www.ventusky.com/?p=42.36;-71.06;6&l=radar
      - https://www.windy.com/-Weather-radar-radar?radar,55.985,-2.796,8
      - https://www.ventusky.com/?p=56.34;-2.79;6&l=feel
      - https://www.ventusky.com/?p=56.34;-2.79;6&l=radar
      - https://flocus.com/online-flip-clock/

      - https://www.spaceweatherlive.com/en/solar-activity.html
      - https://apod.nasa.gov/apod/
      - https://www.star.nesdis.noaa.gov/goes/sector_band.php?sat=G16&sector=eus&band=GEOCOLOR&length=24&dim=1
      - https://science.nasa.gov/mission/webb/what-is-webb-observing/#WhatIsWebbObservingTool
      - https://www.clocktab.com/

      - https://news.ycombinator.com
      - https://finance.yahoo.com/world-indices/
      - https://www.npr.org/
      - https://www.wgbh.org/news
      - https://www.scotsman.com/
      - https://newsmap.ijmacd.com/?edition=US_en
      - https://www.nayuki.io/res/full-screen-clock-javascript/full-screen-clock-analog-with-seconds.svg

      - https://www.mlb.com/standings/
      - https://www.bbc.com/sport/golf/uspga-tour/leaderboard
      - https://www.espn.com/golf/rankings
      - http://www.thecolourclock.com/
    interval: 60
    order: sequential



  - type: novnc
    novnc_url: "http://localhost:6080/vnc.html?host=localhost&port=6080&path=&
autoconnect=true&resize=scale&colordepth=24&password=H@mbixa27"
    position: {row: 2, col: 1}



  - type: rotating_websites
    position: {row: 3, col: 1}
    proxy: true
    urls:
      - https://www.google.com/maps/@41.7268983,-70.3509357,11z/data=!5m1!1e1?entry=ttu&g_ep=EgoyMDI2MDYyOS4wIKXMDSoASAFQAw%3D%3D
      - https://www.google.com/maps/@42.0906689,-70.9852742,10z/data=!5m1!1e1?entry=ttu&g_ep=EgoyMDI2MDYyOS4wIKXMDSoASAFQAw%3D%3D
    interval: 35
    order: sequential


###
#
# OG configuration here for reference
#
# panes:
#   - type: video_playlist
#     position: {row: 1, col: 1}
#     videos:
#       - /media/clips/saber_duels/saber_01.mkv
#       - /media/clips/saber_duels/saber_02.mkv
#     loop: true
#     muted: true
#     order: random        # 'sequential' (default) or 'random'
# 
#   - type: website
#     position: {row: 2, col: 1}
#     url: https://weather.com/local
# 
#   - type: rotating_websites
#     position: {row: 3, col: 1}
#     urls:
#       - https://news.ycombinator.com
#       - https://reddit.com/r/starwars
#     interval: 30
#     order: sequential    # 'sequential' (default) or 'random'
#
#
###

